version: '3'

services:
  app:
    build: .
    depends_on:
      - neo4j
    networks:
      - app-network

  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
